# Generated by Django 3.2.3 on 2021-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20210531_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='score',
            field=models.TextField(blank=True),
        ),
    ]
